name: Python lint & typecheck

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python and enable pip cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install runtime deps and linters
        run: |
          python -m pip install ruff black pyflakes
      #pylint flake8

      - name: Pyflakes (syntax check)
        run: pyflakes addon

      - name: Ruff (lint)
        run: ruff check addon

      - name: Black (format check)
        run: black --check addon

#      - name: Flake8 (style check)
#        run: flake8 addon
#
#      - name: Pylint (code quality)
#        run: pylint addon
